### ISSUE TITLE
Check wether the size obtention during pushes is the most optimal

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/Poseidon252#104]
While I was working withthe `PoseidonTree` I took a look to the internals of the `push()`  function.
https://github.com/dusk-network/Poseidon252/blob/master/src/tree/tree.rs#L85-L96

And I realized that in order to collect the `size` to set the idx of the new entry we do a lot of computation, when we maybe could store the last used idx and just increase it on each iteration.
At the end, the tree is append only so we don't even need to worry about decreasing the number in the deletions since the tree is append-only.

**Comment by ZER0** [comment]
@carlos what do you mean?

**Comment by ZER0** [comment]
This is already fixed.
