### ISSUE TITLE
Poseidon252 doesn't build using "canon" as feature

### ISSUE THREAD

**Issue by ZER0** [dusk-network/Poseidon252#111]
Current master is broken since Poseidon cannot be build using "canon" as feature.

Most likely it has to do with some breaking change  in the dependencies that weren't using proper semver.

**Comment by ZER0** [comment]
See also #110

Most of the errors are related to canon's trait bound not satisfied.

```
error[E0277]: the trait bound `L: canonical::canon::Canon<S>` is not satisfied
  --> src/tree/tree.rs:32:35
   |
32 | impl<L, A, S, const DEPTH: usize> AsRef<NStack<L, A, S>>
   |                                   ^^^^^^^^^^^^^^^^^^^^^^ the trait `canonical::canon::Canon<S>` is not implemented for `L`
   |
  ::: /Users/zer0/.cargo/registry/src/github.com-1ecc6299db9ec823/nstack-0.7.0/src/lib.rs:25:8
   |
25 |     T: Canon<S>,
   |        -------- required by this bound in `NStack`
   |
help: consider further restricting this bound
   |
35 |     L: PoseidonLeaf<S> + canonical::canon::Canon<S>,
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by vlopes11** [comment]
This commit upgraded canon to 0.4 and was minor for microkelvin

https://github.com/dusk-network/microkelvin/commit/efde6505ba5a1774dee0fa077bc12427ea487111#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542

**Comment by vlopes11** [comment]
As discussed, the solution is to update all the versions from this PR:
https://github.com/dusk-network/microkelvin/pull/32
