### ISSUE TITLE
Tree positions should take `u64`

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/Poseidon252#116]
The constrained environments `usize` may use `u32` for indexes.

For some cases - specially the genesis contract transfer tree - we may need to have more than 2^32 leaves in a tree. These last elements will be truncated, generating a critical inconsistency.

#### Proposed solution

All methods of the Poseidon tree must accept `u64` instead of `usize` as arguments

**Comment by ZER0** [comment]
This is solved.
