### ISSUE TITLE
Peculiar naming convention: why add `Failed` as suffix? 

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/Poseidon252#140]
Wondering why this peculiar naming convention: why add `Failed` at suffix? It's not very idiomatic. Not suggesting to change now at all (it would be a MASSIVE breaking change) it just looks a bit weird. Maybe we could change before the release `1.0`?

_Originally posted by @ZER0 in https://github.com/dusk-network/Poseidon252/pull/131#discussion_r622329371_

We should consider changing the naming convention for the errors before we hit `v1.0.0`

**Comment by moCello** [comment]
Erros with suffix 'Failed' don't exist anymore
