### ISSUE TITLE
Set toolchain-file version to 2021-06-06

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/Poseidon252#149]

**Comment by dannywillems** [comment]
Also, dusk-bytes must be set to the version `=0.1.3` and I had to use `nightly-2021-05-09`.

**Comment by CPerezz** [comment]
> Also, dusk-bytes must be set to the version `=0.1.3` and I had to use `nightly-2021-05-09`.

Hi @dannywillems . By default, `cargo` takes the latest patch avaliable. Which basically means that specifying `0.1` in `Cargo.toml` means: Pick the latest patch (>=0.1.X).

So unless we yank the latest versions of `dusk-bytes` (which is not gonna happen) that should not be a problem. Although we should maybe specify just `0.1.3` so that nothing older get's never used in case is cached. But the probability is really low IMO.
