### ISSUE TITLE
Add sponge helper to take ref bytes as argument

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/poseidon252#169]
**Describe what you want implemented** 
Need a function that will convert arbitrary slices of bytes into a `BlsScalar`

**Describe "Why" this is needed**
We are limited by scalars when actually anything could be hashed by poseidon, having the proper implementation available.

**Describe alternatives you've considered**
Duplicating code everywhere with different scalar aggregator strategies that might lead to inconsistencies between libraries.

**Additional context**
We need to perform a hash of the contract id and transaction in the hosted environment of rusk-vm to calculate the transaction hash:
https://github.com/dusk-network/rusk/issues/402

**Comment by moCello** [comment]
Closing as from `dusk-bls12_381` `v0.13` we introduced `BlsScalar::hash_to_scalar` to hash an arbitrary slice of bytes into a scalar and [dusk-network/rusk#402](https://github.com/dusk-network/rusk/issues/402) is completed.
