### ISSUE TITLE
Test fails at Ubuntu 20.04

### ISSUE THREAD

**Issue by hyemmie** [dusk-network/poseidon252#174]
**Describe the bug**
 Test passes on local MacOS (M1), but it fails on Ubuntu 20.04.
Proof verification is unavailable.

**To Reproduce**
Just cloned this repo and run `cargo test` on Ubuntu 20.04

**Logs/Screenshot**
![Screen Shot 2022-07-06 at 3 10 59 PM](https://user-images.githubusercontent.com/44224497/177488955-1ac8382b-e765-4b5a-9a43-6d87d5fd01f6.png)

![Screen Shot 2022-07-06 at 3 13 17 PM](https://user-images.githubusercontent.com/44224497/177489008-38c9714d-b44a-4fe2-89b9-f347f1d6eb99.png)

**Platform**
 - Architecture: x86_64
 - OS: Linux

**Additional context**

**Comment by xevisalle** [comment]
Hi @hyemmie , I tried to replicate the error in different environments (ubuntu, debian, on arm and on intel...) and all the tests pass. Maybe is there some other information you can provide? Are you overriding the rust toolchain by any chance? And, which version of rust are you using?

**Comment by hyemmie** [comment]
hello @xevisalle . thx for checking my issue.
<img width="316" alt="Screen Shot 2022-07-09 at 11 12 23 AM" src="https://user-images.githubusercontent.com/44224497/178087816-59d1eac2-8707-428e-9930-b2a41aed8066.png">

<img width="413" alt="Screen Shot 2022-07-09 at 11 15 11 AM" src="https://user-images.githubusercontent.com/44224497/178087895-a40294e6-c48a-4e15-bfaf-ab828b9a707b.png">

currently using 1.58.0-nightly version and overriding nightly-2021-10-28-x86_64 
is nightly version unavailable for dusk-plonk?

**Comment by ZER0** [comment]
@moCello @ureeves can you have a look at this too…?

**Comment by ureeves** [comment]
I ran the tests using the following rust versions on an ubuntu 20.04 container. I'm also on `x86_64`.

- `1.68.0-stable`
- `1.70.0-nightly`

All seems ok to me. The current HEAD does not build in `1.58.0` anymore. However, we also don't claim an MSRV, and the assumption is we're using at least latest `stable`.

I will close this issue. @hyemmie if you still think this is a problem feel free open a new issue.
