### ISSUE TITLE
Restructure crate features

### ISSUE THREAD

**Issue by ureeves** [dusk-network/poseidon252#184]
**Describe what you want implemented** 
The features of a crate should be named accordingly to the features they enable, and not the names or technicalities of its dependencies. I propose a restructuring of the features of this crate.

**Describe "Why" this is needed**
Currently the features included with this crate are:
```text
default
alloc
rkyv-impl
```

Almost the entire crate sits behind the `alloc` feature with following exceptions:
```text
cipher::PoseidonCipher                                                                                   
perm_uses::two_outputs                                                                                   
sponge::hash                                                                                             
sponge::truncated::hash 
```

I propose that this is terribly confusing, and as such we should rethink the features of the crate.

**Comment by moCello** [comment]
I propose to:
- remove the default feature
- add cipher feature for cipher
- add zk features for all gadgets
- leave rkyv-impl feature as is
