### ISSUE TITLE
Store the root of a branch seperately to the levels

### ISSUE THREAD

**Issue by moCello** [dusk-network/poseidon252#189]
**Describe what you want implemented** 
Rethink the way we store the root in the `PoseidonBranch`.

**Describe "Why" this is needed**
At the moment the root of the `PoseidonBranch` is stored in the last level of the branch at the index 1. Ideally we want the root stored separately to the levels and not as an additional level.
This is also an issue due to the `rkyv` implementations. Since it is now a `Vec`, `PoseidonBranch<17>` would parse in the exact same way as `PoseidonBranch<16>` for example.

**Describe alternatives you've considered**
We could also want to store the levels not as a `Vec` but as an array instead.

**Additional context**
N/A

**Comment by ureeves** [comment]
This is also an issue due to the `rkyv` implementations. Since it is now a `Vec`, `PoseidonBranch<17>` would parse in the exact same way as `PoseidonBranch<16>` for example.
