### ISSUE TITLE
Implement digest

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/Poseidon252#2]
Implement https://crates.io/crates/digest for interop with different systems who requires crypto hashes

**Comment by ZER0** [comment]
It was discussed, but I'm not sure we can, since `digest` works with an arbitrary number of bytes, where `Poseidon252`/ `Hades252` is made to works solely with scalars… One solution could just panic if we pass a slice that is not 32 bytes, but it sounds horrible.

**Comment by vlopes11** [comment]
We can as an alternative consume the stream of bytes, get chunks of 31 bytes, transform these chunks into Scalars and then input these Scalars.

The digest crate is used for interop with many rust crypto implementations, including Dalek. This is a method that I really need to use:

https://docs.rs/curve25519-dalek/2.0.0/curve25519_dalek/scalar/struct.Scalar.html#method.from_hash

**Comment by ZER0** [comment]
Waiting for @krl to reply if it's needed for kelvin.

**Comment by CPerezz** [comment]
@ZER0 @krl is this still needed? Or can it be closed now that we're refactoring it?

**Comment by krl** [comment]
This is not needed for kelvin

**Comment by CPerezz** [comment]
Closing then. Thanks!!
