### ISSUE TITLE
Implement Non-Sparse Merkle tree structures

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/Poseidon252#21]
Once https://github.com/dusk-network/kelvin/issues/37 is closed, we should implement this new types of Merkle Trees within this library and replace the actual Sparse Merkle Trees that we're using now.

On this way, we can have fixed-size branches (height is always the same) so the Proofs can always be obtained using the same `PreProcessedCircuit`.

**Comment by krl** [comment]
This has been solved with https://github.com/dusk-network/nstack

Note, instead of having the tree be always of the same length, we can still keep the performance of the minimal tree required, just adding the extra branch padding when constructing the proof.

**Comment by CPerezz** [comment]
Then this should be implemented here. SInce this is the lib that handles the logic between proofs and branches.

Now this is working with the `NarrowTree` structure. 
This is then guaranteed to produce branches of the same amount of levels always? Due to changes in the NarrowTree i mean.

Anyways, we need to update the versions of kelvin and kelvin-hamt.
