### ISSUE TITLE
What is the `PrimeFieldModulus` data used by this library.

### ISSUE THREAD

**Issue by 99Kies** [dusk-network/poseidon252#223]
I want to use the same `PrimeFieldModulus` as `circom `to continue the calculation what should I do?

![image](https://github.com/dusk-network/Poseidon252/assets/45918704/646fe9af-33e9-46e7-a1f5-2beb73ae39fc)

**Comment by moCello** [comment]
This library works on `BlsScalar` as defined in [dusk-bls12_381](https://github.com/dusk-network/bls12_381). The modulus for bls-scalars can be found [here](https://github.com/dusk-network/bls12_381/blob/master/src/scalar.rs#L86-L93)
