### ISSUE TITLE
Re-design hades permutation

### ISSUE THREAD

**Issue by moCello** [dusk-network/poseidon252#243]
#### Summary
Expose only `permute` and `permute_gadget` functions (and `WIDTH`) from `hades` module.
Edit: After a comment from @xevisalle we decided to only expose the `WIDTH` from the hades module to the public API.

With this change we can refactor the permutation designs internally without a breaking change, if desired, in the future.

**Comment by moCello** [comment]
Following up the comment from https://github.com/dusk-network/Poseidon252/pull/242#discussion_r1461953435 
@xevisalle do you think the entire permutation functions should better be private?

**Comment by xevisalle** [comment]
> Following up the comment from [#242 (comment)](https://github.com/dusk-network/Poseidon252/pull/242#discussion_r1461953435) @xevisalle do you think the entire permutation functions should better be private?

will someone ever want to use hades without poseidon? as it is optimized for our implementation, and now it is even part of the poseidon crate, I guess it's unlikely to happen. In the future we can set public functions to change Hades configurations, but by now I would keep it private.

**Comment by moCello** [comment]
I agree. I'll only expose the `WIDTH` then.
