### ISSUE TITLE
Create general datastructure PoseidonTree, for storing general zk-friendly datastructures

### ISSUE THREAD

**Issue by krl** [dusk-network/Poseidon252#25]
In order to generalize over different tree types, we need a structure that generalize over different entities that we want to store, and the length of the proof branches.

The goal is to be able to write `PoseidonTree<Note>`, `PoseidonTree<Nullifier>` and specify the branch depth.

`PoseidonTree<T>` needs `T` to implement the trait `AsScalar`, which calculates a scalar based on the type.

**Comment by ZER0** [comment]
I wasn't part of the conversation, so I'm asking here: is there a reason why we should implement a trait `AsScalar` for `T` instead of actually have `T: Into<Scalar>`…? (Or `TryInto` if it can fails)

**Comment by krl** [comment]
Into consumes it's argument, so either &T: Into<Scalar> or a custom trait, either way is fine, we can discuss this further as an impl detail, but in general anything will work that produces a scalar (or StorageScalar) without consuming the original T.

**Comment by CPerezz** [comment]
`TryInto` would be needed, I do think it's a must, specially because we have libs like BlindBid which encoding procedures can fail.

Can you add it into #28 @krl ?

**Comment by krl** [comment]
Disagreed. A failed TryInto would fail inside the tree-annotation logic, and it would be a mess to deal with. Since we control the types, we should just make invalid states impossible to construct.

**Comment by krl** [comment]
And note, the Into<StorageScalar> should be implemented on &T, not T

**Comment by CPerezz** [comment]
Yep, got it!
