### ISSUE TITLE
Normalize the Poseidon's versions 

### ISSUE THREAD

**Issue by ZER0** [dusk-network/Poseidon252#33]
The Poseidon's version tag in github starts from `v1.0.0` then goes to `v0.1.0` and jump directly to `v5.0.0`.

We should probably normalize them, adding the tags for version `v0.2.0`, `v0.3.0` and `v0.4.0` to the proper commits – assuming the  versions bump was correctly made in `Cargo.toml`, and maybe rename the tag of `v1.0.0` to `legacy` or something like that, but not a version number: given a different version would clash with `Cargo.toml` content, but it might be worth to keep a reference to that commit.

**Comment by CPerezz** [comment]
@vlopes11 @ZER0 could you check if it's ok now?

**Comment by CPerezz** [comment]
Closed since it has been solved.
