### ISSUE TITLE
Merkle opening constraints

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/Poseidon252#56]
The number of used constraints for a merkle opening proof should be around 22k

Review if this is according on the implementation

**Comment by CPerezz** [comment]
Any news on that @vlopes11 ?? 

Have you had time to take a look?

**Comment by CPerezz** [comment]
We finally discovered where the big amount of gates was coming from.

https://github.com/dusk-network/Hades252/pull/68 closes this issue.
