### ISSUE TITLE
Refactor Poseidon's API module path

### ISSUE THREAD

**Issue by ZER0** [dusk-network/Poseidon252#69]
We should move to Rust 2018 module definition also in Poseidon.

Most importantly, we have to fix the module path of the `sponge_hash` function. Currently we have:
```rust
use poseidon252::sponge::sponge::sponge_hash;
```
Where `sponge` is written three time, that's ridiculous. It's starting to spread in all our repos since we're using a lot the sponge's hash function; that's why we need to refactor as soon is doable.

The idea would be having something like:
```rust
use poseidon252::sponge::hash;
```

The same is applying for  the gadget, so instead of:

```rust
use poseidon252::sponge::sponge::sponge_hash_gadget
```
it should be:
```rust
use poseidon252::sponge::gadgets::hash
```

The module path would be more clear, and we'll still have no naming conflict since we can import just `sponge`, so we'll have a code that instead of:

```rust
// here we're typing `sponge` four times
use poseidon252::sponge::sponge::{sponge_hash, sponge_hash_gadget};

sponge_hash(&[…]);
sponge_hash_gadget(&[…])
```

We'll have:
```rust
use poseidon252::sponge;

sponge::hash(&[…]);
sponge::gadgets::hash(&[…])
```

Of course you can always import directly the gadget or the hash if there is no conflict.

**Comment by ZER0** [comment]
Looks to me we already did that, let's confirm with @vlopes11 and @CPerezz

**Comment by CPerezz** [comment]
Yep. We can close this @ZER0

**Comment by CPerezz** [comment]
New API exported:
```rust
#[cfg(feature = "std")]
pub use sponge::sponge_gadget as gadget;
pub use sponge::sponge_hash as hash;
```
