### ISSUE TITLE
Port `PoseidonTree` to microkelvin

### ISSUE THREAD

**Issue by ZER0** [dusk-network/Poseidon252#84]

**Comment by vlopes11** [comment]
Blocked by https://github.com/dusk-network/bls12_381/issues/36

**Comment by vlopes11** [comment]
Getting "the trait `canonical::canon::Canon<MemStore>` is not implemented for `MockAnnotation`" even if `Canon<MemStore>` is implemented for `MockAnnotation`

https://github.com/dusk-network/microkelvin-poseidon/blob/vlopes11/poseidon/src/lib.rs

**Comment by ZER0** [comment]
I assumed you already checked with `cargo tree` that you don't have multiple version of canon in the dependency tree? From the sound of it looks like the usual explanation.

**Comment by ZER0** [comment]
> I assumed you already checked with `cargo tree` that you don't have multiple version of canon in the dependency tree? From the sound of it looks like the usual explanation.

For future reference, me and @vlopes11 debug it during the 2nd part of the stand up, it was a nested dependency that still used the crates version of canonical instead of the local one used for development.

To avoid that, we add a `[patch`] section at the end of the `Cargo.toml` to point all canonical requires to the local version.

**Comment by CPerezz** [comment]
That should be closed via #83 right @vlopes11 ?? If that's the case, close this please.

**Comment by CPerezz** [comment]
Closing this since it's sure now that we are working on the Bid tree that is done.
